# Generated by Django 4.2.7 on 2023-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileauth', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
